---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-healthy
  labels:
    app: nginx-healthy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-healthy
  template:
    metadata:
      labels:
        app: nginx-healthy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-broken
  labels:
    app: nginx-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-broken
  template:
    metadata:
      labels:
        app: nginx-broken
    spec:
      containers:
        - name: nginx
          image: nginx:does-not-exist-999
          ports:
            - containerPort: 80
